language: c

os:
  - linux
  - osx

compiler:
  - clang

matrix:
  allow_failures:
    - os: linux

addons:
  apt:
    sources:
      - sourceline: 'ppa:plt/racket'
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - llvm-6.0-dev
      - racket

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install llvm && brew install racket; fi
  - echo -en 'travis_fold:start:raco\\r'
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then raco setup; else sudo raco setup; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then raco pkg install --auto compiler-lib; fi
  - echo -en 'travis_fold:end:raco\\r'

script:
  - raco test racket-llvm.rkt
